blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

bookmark:
    resource: "@BookmarkBundle/Resources/config/routing.yml"
    prefix:   /book

job:
    resource: "@JobBundle/Resources/config/routing.yml"
    prefix:   /job

note:
    resource: "@NoteBundle/Resources/config/routing.yml"
    prefix:   /note

bid:
    resource: "@BidBundle/Resources/config/routing.yml"
    prefix:   /bid

review:
    resource: "@ReviewBundle/Resources/config/routing.yml"
    prefix:   /review

project:
    resource: "@ProjectBundle/Resources/config/routing.yml"
    prefix:   /task

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

homepage:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /homepage

logout:
    path: /logout

offer:
    resource: "@OfferBundle/Resources/config/routing.yml"
    prefix:   /offer

portfolio:
    resource: "@PortfolioBundle/Resources/config/routing.yml"
    prefix:   /portfolio



